source 'https://github.com/ShiKaiMing/SKYSpec.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '10.0'

target 'SwipeViewModule_Example' do
  pod 'SwipeViewModule', :path => '../'
#  pod 'SwipeViewModule'
end
